### PR TITLE
feat: each Rule defines whether it's enabled by default

### PR DESCRIPTION
**Pull request by kgilpin**
Remove the need for `default.yml`, by enabling each Rule to declare whether it's default-enabled.

Default-enabled rules can be disabled in the configuration:

```
disableDefault:
- http-500
```

This way, a scanner configuration file does not have to re-declare all the default rules.

### CODE REVIEW

**Comment by dividedmind** [comment]
I don't like this idea. The default configuration file serves as a central reference for the available configuration and a useful base for the user's configuration.

**Comment by kgilpin** [comment]
How are we going to enable new scanners? Once a user has decided to provide
their own configuration, they will have to modify it to add any new rules
that we come out with.

**Comment by kgilpin** [comment]
I will convert this to a Draft until we have a chance to discuss it.

**Comment by dividedmind** [comment]
> How are we going to enable new scanners? Once a user has decided to provide their own configuration, they will have to modify it to add any new rules that we come out with.

Not necessarily. The final configuration would simply be `{...defaultConfig, ...userConfig}` (maybe globalConfig, too, eg. `~/.config/appland/scanner.yaml`). This is how most tools work and I think it's pretty expected.

**Comment by dividedmind** [comment]
> Ok so you’re fine with merging the configs you just want the default to be more explicit?

Yes! And also centralized and in the same format that the user config. Ideally it would also commented so that the user can copy it out and modify it as needed without needing to use an external reference. But even if the user doesn't do that it still serves as a nice reference in itself (of both the default configuration and what's possible to configure).

**Pull request closed without merging**
